export * from './getLocationByBMap'
export * from './launchWxMiniProgram'
export * from './licenseOCR'
export * from './openLivePlayer'
export * from './openLiveRoom'
export * from './openVideo'
export * from './voiceInput'
export * from './wxShare'
